AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'coverage/**/*'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Layout/LineLength:
  Max: 120
